# Generated by Django 4.2.28 on 2026-02-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='delivery_timeline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='destination_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='mandatory_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='preferred_incoterms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='product_specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='required_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='target_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('QUOTATION_SENT', 'Quotation Sent'), ('QUOTATION_APPROVED', 'Quotation Approved'), ('MOU_SIGN', 'MOU Sign'), ('POST_QUOTATION_FOLLOW_UPS', 'Post Quotation Follow ups'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PAYMENT_TERMS', 'Payment Terms'), ('PAYMENT_RECEIVED', 'Payment Received'), ('COMMISSION_RECEIVED', 'Commission Received'), ('ORDER_COMPLETED', 'Order Completed')], default='QUOTATION_SENT', max_length=30),
        ),
    ]
