# Generated by Django 4.2.28 on 2026-02-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buyer_delivery_timeline_buyer_destination_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
