# Generated by Django 6.0.2 on 2026-02-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_supplier_account_name_supplier_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='turnover_2y',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='iec_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='turnover_2y',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
