# Generated by Django 6.0.2 on 2026-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_buyer_turnover_2y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product_available',
            field=models.TextField(blank=True, null=True),
        ),
    ]
