# Generated by Django 6.0.2 on 2026-03-06 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supplier_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('QUOTATION_SENT', 'Quotation Sent'), ('QUOTATION_APPROVED', 'Approved'), ('MOU_SIGN', 'MOU Sign'), ('POST_QUOTATION_FOLLOW_UPS', 'Follow-ups'), ('ORDER_CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PAYMENT_TERMS', 'Payment Terms'), ('PAYMENT_RECEIVED', 'Payment Received'), ('COMMISSION_RECEIVED', 'Commission Received'), ('ORDER_COMPLETED', 'Order Completed')], default='QUOTATION_SENT', max_length=30),
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
